main:
  baseUrl: "https://api.staging.finnotech.ir"

services:
  - name: "billingInquiry"
    url: "/billing/v2/clients/%s/billingInquiry"
    method: "get"
    payload:
      parameter: string
      secondParameter: string
      type: string