main:
  address: "https://apibeta.finnotech.ir"
  sandboxAddress: "https://sandboxapi.finnotech.ir"

services:
  - name: "cardToIban"
    url: "{address}/facility/v2/clients/{clientId}/cardToIban"
    method: "get"
    payload:
      trackId: string
      card: string
      version: string

  - name: "billingInquiry"
    url: "{address}/billing/v2/clients/{clientId}/billingInquiry"
    method: "get"
    payload:
      trackId: string
      type: string
      parameter: string
      secondParameter: string

  - name: "mobileCardVerification"
    url: "{address}/kyc/v2/clients/{clientId}/mobileCardVerification"
    method: "post"
    payload:
      trackId: string
      mobile: string
      card: string

  - name: "guarantyInquiry"
    url: "{address}/credit/v2/clients/{clientId}/users/{nid}/guarantyInquiry"
    method: "get"
    payload:
      trackId: string
      nid: string

  - name: "token"
    url: "{address}/dev/v2/oauth2/token"
    method: "post"
    payload:
      grant_type: string
      nid: string
      scopes: string
