main:
  address: "https://apibeta.finnotech.ir"
  sandboxAddress: "https://sandboxapi.finnotech.ir"

services:
  - name: "cardToIban"
    url: "{address}/facility/v2/clients/{clientId}/cardToIban"
    method: "get"
    payload:
      trackId: string
      card: string
      version: string
  - name: "billingInquiry"
    url: "{address}/billing/v2/clients/{clientId}/billingInquiry"
    method: "get"
    payload:
      trackId: string
      type: string
      parameter: string
      secondParameter: string
