version: '3.7'
services:
  test:
    build:
        context: .
        dockerfile: Dockerfile.dev
    depends_on:
      - redis

    volumes:
      - /usr/app/node_modules
      - .:/usr/app

    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: 'redis'
